### ISSUE TITLE
Dashboard / settings / export page mobile responsive

### ISSUE THREAD

**Issue by ThePlugJumbo** [ThePlugJumbo/openops#18]
Add media queries to make the header, dashboard page, and footer have a desktop, tablet, and mobile view.  use lg: md: tailwind prefixes.

**Comment by M1racle04** [comment]
please assign, thanks

**Comment by ThePlugJumbo** [comment]
@M1racle04 assigned, thanks.

**Comment by ThePlugJumbo** [comment]
I'm going to knock this out so some more tickets can get added @M1racle04
