### ISSUE TITLE
Change footer link to "Report a bug"

### ISSUE THREAD

**Issue by ThePlugJumbo** [ThePlugJumbo/openops#25]
Currently, it says "report an issue".  This should say "report a bug".

**Comment by Jose-Cera** [comment]
I can do it.

**Comment by ThePlugJumbo** [comment]
Perfect, thanks.  Assigned you to this task.

**Comment by ThePlugJumbo** [comment]
@Jose-Cera any updates on this one?

**Comment by Jose-Cera** [comment]
Currently I'm busy with school, but next week I can make it.

**Comment by ThePlugJumbo** [comment]
No problem, il leave it open.  Good luck @Jose-Cera
