### ISSUE TITLE
Change header links gap

### ISSUE THREAD

**Issue by ThePlugJumbo** [ThePlugJumbo/openops#27]
Currently, the links in the header component have a gap-3 class.  This should be changed to gap-2.

**Comment by rabbanirizwan** [comment]
@ThePlugJumbo  kindly assign me this one

**Comment by ThePlugJumbo** [comment]
Perfect, thank you @rabbanirizwan.  I have assigned you.

**Comment by rabbanirizwan** [comment]
@ThePlugJumbo  https://github.com/ThePlugJumbo/openops/pull/32
