### ISSUE TITLE
handleCustomization should be handleAlert

### ISSUE THREAD

**Issue by ThePlugJumbo** [ThePlugJumbo/openops#28]
The function name should be changed, along with the call of the function in /index.js.  Until there are cards to customize the function should be called handleAlert.

**Comment by rabbanirizwan** [comment]
@ThePlugJumbo  I wanted to work on this

**Comment by ThePlugJumbo** [comment]
Alright, thank you @rabbanirizwan.  Assigned.

**Comment by rabbanirizwan** [comment]
@ThePlugJumbo  https://github.com/ThePlugJumbo/openops/pull/31
