### ISSUE TITLE
Dashboard state for if user has no settings yet

### ISSUE THREAD

**Issue by ThePlugJumbo** [ThePlugJumbo/openops#3]
If the user has no settings yet in their /settings page, the /index page should show a view linking to the settings page.  This will be linked later using either useContext, or a local .txt file, but just create the view for now.

**Comment by adrianmarinwork** [comment]
I can take care of this if you want me to

**Comment by ThePlugJumbo** [comment]
That would be great, thanks.  I assigned you to this issue.

**Comment by ThePlugJumbo** [comment]
@adrianmarinwork that issue was probably too difficult for a first issue, my bad.  I'll make sure to add easier ones.

**Comment by adrianmarinwork** [comment]
I can still take care of this if you want, it doesn't really look that difficult and I have experience with this kind of things :D

**Comment by ThePlugJumbo** [comment]
Alright, love to hear that 👍.  Il leave it open.  Thanks again

**Comment by adrianmarinwork** [comment]
Okay, after reading the code and looking the state of it, before doing this you should finish some logics before, like where you are going to store the saved configurations for user and the API that returns you the configuration of the user has saved.
So this functionality is something more like of the future. I thougth you had more code done. I'm sorry.

**Comment by ThePlugJumbo** [comment]
no problem... I'll fix up those issues then add this ticket as a much easier task in a few days...  We are going to use a local json file for what you mentioned... Sorry about that 😬
