### ISSUE TITLE
Create a modal for entering user's API key in /settings

### ISSUE THREAD

**Issue by ThePlugJumbo** [ThePlugJumbo/openops#37]
Pressing the configure button will pop up a modal, with inputs to enter the API keys for each card.  Right now, just create the modal.  The logic can be added in a separate ticket.

**Comment by adrianmarinwork** [comment]
Hello, after taking a look at the TailwindCSS framework as it's only a CSS framework, it does not have a predefined component to pop up a modal, if you don't want to do it handmade, you could add component frameworks that work with Tailwind like [Tailwind Elements](https://tailwind-elements.com/quick-start/) or [Flowbite](https://flowbite.com/docs/getting-started/quickstart/). 
What do you think?

**Comment by ThePlugJumbo** [comment]
I would like to do it handmade.  I can make the general modal component after school so it would be easier to customize.

**Comment by adrianmarinwork** [comment]
Hello, how is it going, are you going to take care of this issue?
