### ISSUE TITLE
Footer links should open in new tab

### ISSUE THREAD

**Issue by ThePlugJumbo** [ThePlugJumbo/openops#43]
Add the following props to the footer links: target="_blank", rel="noopener noreferrer".  Currently, they open in the same tab.

**Comment by adrianmarinwork** [comment]
Hey, how you doing?
I can take care of this issue as well of issue #37 if you want!

**Comment by ThePlugJumbo** [comment]
Doing great, and you?
That would be great, thanks.  Assigned both. @adrianmarinwork
