### ISSUE TITLE
Header text should be inside an <h6>

### ISSUE THREAD

**Issue by ThePlugJumbo** [ThePlugJumbo/openops#44]
Currently, inside header.js, there is:
< Link >
    OpenOps
</ Link >.

This should be :
< Link >
    < h6 >
        OpenOps
    </ h6 >
</ Link >

**Comment by andyosei12** [comment]
Hi, I will like to work on this

**Comment by andyosei12** [comment]
@ThePlugJumbo  Should all navigation links in the header be wrapped in h6 as well before the svg icons

**Comment by andyosei12** [comment]
Noted
