### ISSUE TITLE
Closing navigation menu on medium and small screens

### ISSUE THREAD

**Issue by andyosei12** [ThePlugJumbo/openops#49]
On medium and small screens, the close button/icon does not close the navigation menu. The navigation menu stays open.

The close button on small and medium screens should close the navigation menu.

**Comment by ThePlugJumbo** [comment]
@AnthonyHad That would be awesome, thank you.  Let me know if you encounter any issues along the way 👍.  I assigned this issue to you.

**Comment by AnthonyHad** [comment]
@ThePlugJumbo  Thanks a lot ! Will definitely do.

**Comment by AnthonyHad** [comment]
@ThePlugJumbo Done!

**Comment by ThePlugJumbo** [comment]
closed
