### ISSUE TITLE
Add max width and margin to error labels

### ISSUE THREAD

**Issue by ThePlugJumbo** [ThePlugJumbo/openops#57]
On lines 17 and 18 of settings.js and lines 11 and 12 of index.js: These divs should have className="max-w-screen-xl mx-auto".  Currently, these errors are overflowing the dashboard.

**Comment by chasemi** [comment]
Could I be assigned this issue?

**Comment by ThePlugJumbo** [comment]
@chasemi Assigned, thanks.
